# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dronesensor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='creation_date',
        ),
    ]
