# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 15:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronesensor', '0002_remove_point_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
