# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dronesensor', '0003_point_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='date',
            new_name='creation_date',
        ),
    ]
